version: '3.8'

services:
  dev-db:
    container_name: database
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: nest
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8000:80
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf

