version: '3.8'

services:
  devdb:
    container_name: database
    image: postgres:13-alpine
    ports:
      - 5432:5432
      - 5556:5555
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: nest

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - devdb
      - client

  client:
    # volumes:
    #   - ./client:/app
    build: ./client
    depends_on:
      - devdb
      - api
    
    

  api:
    # volumes:
    #   - ./api:/app
    depends_on:
      - devdb
    build: ./api

